name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # - uses: webfactory/ssh-agent@v0.9.0
    #  with:
    #  ssh-private-key: ${{ secrets.DEPS_SSH_KEY }}

    - uses: astral-sh/setup-uv@v6
    - uses: actions/setup-python@v5
      with:
        python-version-file: .python-version

    - run: uv sync --locked --all-groups

    - name: Ruff formatting
      run: uv run ruff format --check .

    - name: Ruff linting
      run: uv run ruff check .

    - name: Pyright
      run: uv run pyright

    - name: Tests
      run: uv run pytest -q

